apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170418057
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170418057
    app.kubernetes.io/part-of: test-app-170418057
  name: java-quarkus-1704180577f8l
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-quarkus-170418057
    weight: null
status: {}
