apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170418057
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170418057
    app.kubernetes.io/part-of: test-app-170418057
  name: java-quarkus-170418057
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170418057
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170418057
    spec:
      containers:
      - image: quay.io/hacdev/iqqwmpeb-tenant/test-app-170418057/java-quarkus-170418057@sha256:193927a6d402a11b82baa5e2915329d7a75136181c8415cfcf9e1ab2a4f78fba
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
